export const signIn = {
  SIGN_IN_PENDING: 'SIGN_IN_PENDING',
  SIGN_IN_FULFILLED: 'SIGN_IN_FULFILLED',
  SIGN_IN_REJECTED: 'SIGN_IN_REJECTED',
};
export const signUp = {
  SIGN_UP_PENDING: 'SIGN_UP_PENDING',
  SIGN_UP_FULFILLED: 'SIGN_UP_FULFILLED',
  SIGN_UP_REJECTED: 'SIGN_UP_REJECTED',
};

export const signOut = {
  SIGN_OUT_PENDING: 'SIGN_OUT_PENDING',
  SIGN_OUT_FULFILLED: 'SIGN_OUT_FULFILLED',
  SIGN_OUT_REJECTED: 'SIGN_OUT_REJECTED',
};
